CREATE DATABASE IF NOT EXISTS dbname;
USE dbname;

CREATE TABLE hellos (
  casual VARCHAR (10),
  formal VARCHAR (10),
  HI_ID BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY(HI_ID)
);

CREATE TABLE goodbyes (
  casual VARCHAR(10),
  formal VARCHAR(10),
  BYE_ID BIGINT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY(BYE_ID)
);